name: CI

on: push

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1.1.0
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint mypy safety
    - name: Lint
      run: make lint
    - name: Typecheck
      run: make typecheck
    - name: Test
      run: make test
    - name: Safety check
      env:
        SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
      run: safety check
